name: Spotify Workspace CI

# 1. ¿Cuándo se va a ejecutar? Cuando ocurra un push a la rama main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ submodule-updated ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Actualizar submódulos al último commit
      run: |
        git submodule update --remote --recursive

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18 
        cache: 'npm'

    - name: Correr Tests del Backend (Node.js)
      run: |
        cd spotify-nodejs
        npm ci 
        npm test -- --passWithNoTests

    - name: Correr Tests del Frontend (Angular)
      run: |
        cd spotify-angular
        npm ci
        npm test -- --watch=false

    # Paso 2: Configurar Docker Compose en el entorno virtual
    - name: Verificar herramientas de Docker
      run: |
        docker --version
        docker compose version

    # Paso 3: Construir las imágenes usando tu docker-compose.yml
    # Esto probará que tanto el Dockerfile de Angular como el de Node compilan sin errores.
    - name: Construir imágenes de Docker
      run: docker compose build